spring.application.name=ecommerce-multivendor-project

spring.datasource.url=jdbc:postgresql://localhost:5432/easymartdb
spring.datasource.username=postgres
spring.datasource.password=jahnavibhat1712
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=5454

#frontend port should be 3000 as set in app config allowed origins
